spring:
  profiles: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心
  client:
    serviceUrl:
      defaultZone: http://106.13.167.168:8080/EurekaServer/eureka